-- executed. Error on table name and column name. Fixed.

---Access Living
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Access Living'), (select id from language where language = 'English'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Access Living'), (select id from language where language = 'Spanish'));
--Adalberto Memorial United Methodist Church
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Adalberto Memorial United Methodist Church'), (select id from language where language = 'Spanish'));
--Advocate Christ Medical Center
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Advocate Christ Medical Center'), (select id from language where language = 'Arabic'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Advocate Christ Medical Center'), (select id from language where language = 'English'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Advocate Christ Medical Center'), (select id from language where language = 'Polish'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Advocate Christ Medical Center'), (select id from language where language = 'Spanish'));
--Advocate United Church of Christ
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Advocate United Church of Christ'), (select id from language where language = 'English'));
--African Community United Methodist Church'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'African Community United Methodist Church'), (select id from language where language = 'English'));
--Alexian Brothers Parish Services'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Alexian Brothers Parish Services'), (select id from language where language = 'English'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Alexian Brothers Parish Services'), (select id from language where language = 'Polish'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Alexian Brothers Parish Services'), (select id from language where language = 'Spanish'));
--American Cancer Society, Chicago Region'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'American Cancer Society, Chicago Region'), (select id from language where language = 'English'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'American Cancer Society, Chicago Region'), (select id from language where language = 'Spanish'));
--Antioch Telegu Church'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Antioch Telegu Church'), (select id from language where language = 'Telugu'));
--B\'nai Yehuda Beth Shalom'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'B\'nai Yehuda Beth Shalom'), (select id from language where language = 'English'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'B\'nai Yehuda Beth Shalom'), (select id from language where language = 'Hebrew'));
--Buddhist International Tzu Chi Relief Foundation (Midwest)'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Buddhist International Tzu Chi Relief Foundation (Midwest)'), (select id from language where language = 'Spanish'));
--Central Spanish Baptist Church'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Central Spanish Baptist Church'), (select id from language where language = 'English'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Central Spanish Baptist Church'), (select id from language where language = 'Spanish'));
--Chinmaya Mission Chicago-Badri'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Chinmaya Mission Chicago-Badri'), (select id from language where language = 'English'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Chinmaya Mission Chicago-Badri'), (select id from language where language = 'Hindi'));
--Congregational United Church of Christ of Arlington Heights'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Congregational United Church of Christ of Arlington Heights'), (select id from language where language = 'English'));
--Cornerstone Community Outreach'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Cornerstone Community Outreach'), (select id from language where language = 'English'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Cornerstone Community Outreach'), (select id from language where language = 'Polish'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Cornerstone Community Outreach'), (select id from language where language = 'Spanish'));
--Edgewater Presbyterian Church'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Edgewater Presbyterian Church'), (select id from language where language = 'English'));
--Evergreen Presbyterian Church'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Evergreen Presbyterian Church'), (select id from language where language = 'English'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Evergreen Presbyterian Church'), (select id from language where language = 'Korean'));
--Exodus Community Church'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Exodus Community Church'), (select id from language where language = 'English'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Exodus Community Church'), (select id from language where language = 'Korean'));
--Figure Facts LLC'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Figure Facts LLC'), (select id from language where language = 'English'));
--First Baptist Church, Berwyn'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'First Baptist Church, Berwyn'), (select id from language where language = 'English'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'First Baptist Church, Berwyn'), (select id from language where language = 'Polish'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'First Baptist Church, Berwyn'), (select id from language where language = 'Spanish'));
--First Baptist Church, LaGrange'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'First Baptist Church, LaGrange'), (select id from language where language = 'English'));
--First Baptist Church, Park Forest'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'First Baptist Church, Park Forest'), (select id from language where language = 'English'));
--First Congregational Church of Western Springs'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'First Congregational Church of Western Springs'), (select id from language where language = 'English'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'First Congregational Church of Western Springs'), (select id from language where language = 'Spanish'));
--First Evangelical Free Church'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'First Evangelical Free Church'), (select id from language where language = 'English'));
--Grace Calvary United Methodist Church'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Grace Calvary United Methodist Church'), (select id from language where language = 'English'));
--Grace Calvary United Methodist Church- Gospel Cafe'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Grace Calvary United Methodist Church- Gospel Cafe'), (select id from language where language = 'English'));
--Grace Evangelical Lutheran Church'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Grace Evangelical Lutheran Church'), (select id from language where language = 'English'));
--Grace Lutheran Church'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Grace Lutheran Church'), (select id from language where language = 'English'));
--Healthy Dining Chicago Healthy Dining Chicago'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Healthy Dining Chicago Healthy Dining Chicago'), (select id from language where language = 'English'));
--Illinois Faith Based Emergency Preparedness Initiative'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Illinois Faith Based Emergency Preparedness Initiative'), (select id from language where language = 'English'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Illinois Faith Based Emergency Preparedness Initiative'), (select id from language where language = 'Spanish'));
--Inner City Muslim Action Network'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Inner City Muslim Action Network'), (select id from language where language = 'Arabic'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Inner City Muslim Action Network'), (select id from language where language = 'English'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Inner City Muslim Action Network'), (select id from language where language = 'Spanish'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Inner City Muslim Action Network'), (select id from language where language = 'Urdu'));
--Ismaili Center in Chicago'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Ismaili Center in Chicago'), (select id from language where language = 'Arabic'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Ismaili Center in Chicago'), (select id from language where language = 'English'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Ismaili Center in Chicago'), (select id from language where language = 'Farsi'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Ismaili Center in Chicago'), (select id from language where language = 'Hindi'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Ismaili Center in Chicago'), (select id from language where language = 'Urdu'));
--Ismaili Center in Glenview'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Ismaili Center in Glenview'), (select id from language where language = 'Arabic'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Ismaili Center in Glenview'), (select id from language where language = 'English'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Ismaili Center in Glenview'), (select id from language where language = 'Farsi'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Ismaili Center in Glenview'), (select id from language where language = 'Hindi'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Ismaili Center in Glenview'), (select id from language where language = 'Urdu'));
--Jewish Community Emergency Resiliency Team'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Jewish Community Emergency Resiliency Team'), (select id from language where language = 'English'));
--Journey Community Church'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Journey Community Church'), (select id from language where language = 'English'));
--Lutheran General Hospital - Mission and Spiritual'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Lutheran General Hospital - Mission and Spiritual'), (select id from language where language = 'English'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Lutheran General Hospital - Mission and Spiritual'), (select id from language where language = 'Korean'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Lutheran General Hospital - Mission and Spiritual'), (select id from language where language = 'Polish'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Lutheran General Hospital - Mission and Spiritual'), (select id from language where language = 'Russian'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Lutheran General Hospital - Mission and Spiritual'), (select id from language where language = 'Spanish'));
--Lutheran Social Services of Illinois'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Lutheran Social Services of Illinois'), (select id from language where language = 'English'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Lutheran Social Services of Illinois'), (select id from language where language = 'Polish'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Lutheran Social Services of Illinois'), (select id from language where language = 'Spanish'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Lutheran Social Services of Illinois'), (select id from language where language = 'Tagalog'));
--Mosque Foundation'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Mosque Foundation'), (select id from language where language = 'Arabic'));
--North Shore Baptist Church'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'North Shore Baptist Church'), (select id from language where language = 'English'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'North Shore Baptist Church'), (select id from language where language = 'Japanese'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'North Shore Baptist Church'), (select id from language where language = 'Korean'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'North Shore Baptist Church'), (select id from language where language = 'Spanish'));
--Northfield Presbyterian Church'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Northfield Presbyterian Church'), (select id from language where language = 'Korean'));
--Park Ridge Community Church'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Park Ridge Community Church'), (select id from language where language = 'English'));
--Peoples Church of Chicago'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Peoples Church of Chicago'), (select id from language where language = 'English'));
--Pilgrim Faith United Church of Christ'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Pilgrim Faith United Church of Christ'), (select id from language where language = 'English'));
--Polish Community'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Polish Community'), (select id from language where language = 'Polish'));
--St. Anne Church'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'St. Anne Church'), (select id from language where language = 'English'));
--St. Ita Catholic Church'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'St. Ita Catholic Church'), (select id from language where language = 'English'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'St. Ita Catholic Church'), (select id from language where language = 'Spanish'));
--St. James Lutheran Church'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'St. James Lutheran Church'), (select id from language where language = 'English'));
--St. John United Church of Christ'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'St. John United Church of Christ'), (select id from language where language = 'English'));
--St. Pius V. Church'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'St. Pius V. Church'), (select id from language where language = 'Spanish'));
--St. Sylvester Catholic Church'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'St. Sylvester Catholic Church'), (select id from language where language = 'English'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'St. Sylvester Catholic Church'), (select id from language where language = 'Polish'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'St. Sylvester Catholic Church'), (select id from language where language = 'Spanish'));
--Suburban Chicago Interfaith Mental Health Coalition'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Suburban Chicago Interfaith Mental Health Coalition'), (select id from language where language = 'English'));
--The Buddhist Temple of Chicago'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'The Buddhist Temple of Chicago'), (select id from language where language = 'English'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'The Buddhist Temple of Chicago'), (select id from language where language = 'Japanese'));
--The South Church'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'The South Church'), (select id from language where language = 'English'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'The South Church'), (select id from language where language = 'Polish'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'The South Church'), (select id from language where language = 'Spanish'));
--Turning Point'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Turning Point'), (select id from language where language = 'English'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Turning Point'), (select id from language where language = 'Farsi'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Turning Point'), (select id from language where language = 'Japanese'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Turning Point'), (select id from language where language = 'Spanish'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Turning Point'), (select id from language where language = 'Urdu'));
--Unity Lutheran Church'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Unity Lutheran Church'), (select id from language where language = 'English'));
--Unity Northwest Church'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'Unity Northwest Church'), (select id from language where language = 'English'));
--ZAM\'s Hope Community Resource Center'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'ZAM\'s Hope Community Resource Center'), (select id from language where language = 'Arabic'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'ZAM\'s Hope Community Resource Center'), (select id from language where language = 'Hindi'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'ZAM\'s Hope Community Resource Center'), (select id from language where language = 'Spanish'));
insert into organization_language (organization_fk, language_fk) values ((select id from organization where name = 'ZAM\'s Hope Community Resource Center'), (select id from language where language = 'Urdu'));