insert into organization (name, status_fk, create_dttm, activate_dttm) values ('Access Living', '1', now(), now());
insert into organization (name, status_fk, create_dttm, activate_dttm) values ('Advocate Christ Medical Center', '1', now(), now());
insert into organization (name, status_fk, create_dttm, activate_dttm) values ('Advocate Clinical Pastoral Education', '1', now(), now());
insert into organization (name, status_fk, create_dttm, activate_dttm) values ('Advocate Health Care', '1', now(), now());
insert into organization (name, status_fk, create_dttm, activate_dttm) values ('Advocate Parish Nurse Ministry', '1', now(), now());
insert into organization (name, status_fk, create_dttm, activate_dttm) values ('Advocate United Church of Christ', '1', now(), now());
insert into organization (name, status_fk, create_dttm, activate_dttm) values ('African-American Alzheimer&acirc;&euro;&trade;s Outreach Initiative', '1', now(), now());
insert into organization (name, status_fk, create_dttm, activate_dttm) values ('Agape Family Life Center', '1', now(), now());
insert into organization (name, status_fk, create_dttm, activate_dttm) values ('Age Options', '1', now(), now());
insert into organization (name, status_fk, create_dttm, activate_dttm) values ('Alexian Brothers Parish Services', '1', now(), now());
insert into organization (name, status_fk, create_dttm, activate_dttm) values ('Alzheimer\'s Association Greater Illinois Chapter', '1', now(), now());
insert into organization (name, status_fk, create_dttm, activate_dttm) values ('Am I My Brothers Keeper', '1', now(), now());
insert into organization (name, status_fk, create_dttm, activate_dttm) values ('American Heart Association Cultural Health Initiatives', '1', now(), now());
insert into organization (name, status_fk, create_dttm, activate_dttm) values ('American Kidney Fund', '1', now(), now());
insert into organization (name, status_fk, create_dttm, activate_dttm) values ('Antioch Telegu Church', '1', now(), now());
insert into organization (name, status_fk, create_dttm, activate_dttm) values ('Apostolic Church of God', '1', now(), now());
insert into organization (name, status_fk, create_dttm, activate_dttm) values ('Apostolic Faith Church Health Professions Ministry', '1', now(), now());
insert into organization (name, status_fk, create_dttm, activate_dttm) values ('B&acirc;&euro;&trade;nai Yehuda Beth Shalom', '1', now(), now());
insert into organization (name, status_fk, create_dttm, activate_dttm) values ('Beacon Light', '1', now(), now());
insert into organization (name, status_fk, create_dttm, activate_dttm) values ('Bikur Cholim (visiting the sick) training', '1', now(), now());
insert into organization (name, status_fk, create_dttm, activate_dttm) values ('Breast Cancer Network of Strength', '1', now(), now());
insert into organization (name, status_fk, create_dttm, activate_dttm) values ('Buddhist International Tzu Chi Relief Foundation (Midwest)', '1', now(), now());
insert into organization (name, status_fk, create_dttm, activate_dttm) values ('Campaign for Better Health Care', '1', now(), now());
insert into organization (name, status_fk, create_dttm, activate_dttm) values ('Caring for Health', '1', now(), now());