-- clean funny characters
-- spot check

-- &acirc;&euro;&trade; => '
-- &acirc;&euro;" => -
-- &amp; => and


insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('30th Ward - St. James Church', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('A Just Harvest', now(), now(), '1', 'Community Organization');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Access Living', now(), now(), '1', 'Community Organization');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Adalberto Memorial United Methodist Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Advocate Christ Medical Center', now(), now(), '1', 'Heath Care Provider');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Advocate Clinical Pastoral Education', now(), now(), '1', 'Heath Care Provider');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Advocate Health Care', now(), now(), '1', 'Heath Care Provider');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Advocate Parish Nurse Ministry', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Advocate United Church of Christ', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('African Community United Methodist Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('African-American Alzheimer&acirc;&euro;&trade;s Outreach Initiative', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Agape Family Life Center', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Age Options', now(), now(), '1', 'Community Organization');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Alexian Brothers Parish Services', now(), now(), '1', 'Community Organization');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Alzheimer's Association &acirc;&euro;" Greater Illinois Chapter', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Am I My Brothers Keeper', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('American Cancer Society, Chicago Region', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('American Heart Association Cultural Health Initiatives', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('American Kidney Fund', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Antioch Telegu Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Apostolic Church of God', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Apostolic Faith Church Health Professions Ministry', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('B&acirc;&euro;&trade;nai Yehuda Beth Shalom', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Beacon Light', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Bethel Reform Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Bikur Cholim (visiting the sick) training', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Breast Cancer Network of Strength', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Buddhist International Tzu Chi Relief Foundation (Midwest)', now(), now(), '1', 'Community Organization');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Campaign for Better Health Care', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Caring for Health', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('CARRI (Chicago Area Regional Recovery Initiative)', now(), now(), '1', 'Community Organization');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Center for Faith and Health', now(), now(), '1', 'University');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Central Spanish Baptist Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Chicago Chin Baptist Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Chicago Theological Seminary', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Chicago Uptown Ministry', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Chinmaya Mission Chicago-Badri', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Christ Temple Apostolic Faith Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Christ the King Lutheran Church ELCA', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Christian Churches Caring', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Christian Fellowship Flock', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Church of Jesus Christ Latter Day Saints', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Coalition for Quality and Patient Safety of Chicagoland', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Community Health Services and Health Promotion', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Community-Outreach Project', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Congregational Health Partnerships', now(), now(), '1', 'Heath Care Provider');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Congregational Outreach', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Congregational United Church of Christ of Arlington Heights', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Consortium to Lower Obesity in Chicago Children (CLOCC)', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Cornerstone Community Outreach', now(), now(), '1', 'Community Organization');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Council of Islamic Organizations of Greater Chicago', now(), now(), '1', 'Community Organization');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Delegate Church Association of Advocate BroMenn Medical Center', now(), now(), '1', 'Faith Based Network');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('DuPage Department of Public Health', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Ebenezer Baptist', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Ebenezer Lutheran Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Edgewater Presbyterian Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Education and Life Coaching', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Epworth United Methodist Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Evergreen Presbyterian Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Exodus Community Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Faith Caucus', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Faith in Place', now(), now(), '1', 'Community Organization');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Faith Temple COGIC', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Faith United Methodist Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Figure Facts LLC', now(), now(), '1', 'Heath Care Provider');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('First Baptist Church, Berwyn', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('First Baptist Church, LaGrange', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('First Baptist Church, Park Forest', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('First Congregational Church of Western Springs', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('First Evangelical Free Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('First Grace Missionary Baptist Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('First New Bethlehem Community Development Corporation', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Flossmoor Community Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Fourth Presbyterian Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Friendly Visits', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Friendship Baptist Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Gloria Dei Lutheran Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('God Can Ministries', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Grace Calvary United Methodist Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Grace Calvary United Methodist Church- Gospel Cafe', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Grace Evangelical Lutheran Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Grace Lutheran Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Greater Galilee MB Church', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Greater Galilee Missionary Baptist Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Greater Open Door Baptist Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Greater Progressive Missionary Baptist Church Baptist Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Greater St. John Bible Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Greater St. Paul A M E C', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Greater Walters AME Zion Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Hamdard Center for Health and Human Services', now(), now(), '1', 'Community Organization');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Health Initiatives, West Cook Area', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Healthcare Consortium of Illinois', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Healthy Dining Chicago Healthy Dining Chicago', now(), now(), '1', 'Community Organization');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Healthy Spirit Healthy Soul', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Hispanocare - Chicago', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Hyde Park Christian Reformed Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Illinois Faith Based Emergency Preparedness Initiative', now(), now(), '1', 'Government');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Illinois Maternal and Child Health Coalition', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Illinois PIRG', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Illinois Women's Health Registry', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Imagine Chicago', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Inner City Muslim Action Network', now(), now(), '1', 'Community Organization');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Institute for Women's Health Research', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Islamic Community Center', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Islamic Foundation of Villa Park', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Ismaili Center in Chicago', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Ismaili Center in Glenview', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Jesus Name Apostolic Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Jewish Child and Family Services', now(), now(), '1', 'Community Organization');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Jewish Community Emergency Resiliency Team', now(), now(), '1', 'Community Organization');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Jewish Healing Network of Chicago', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Jewish School-Based Wellness Initiative', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Joshua Missionary Baptist Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Journey Community Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Joy To Be Fit Gospel Aerobics Ministry', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Kenwood UCC', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Kimball Ave. Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('La Academia', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Lakeview Presbyterian Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Latino Community Program', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('LaVerne Barnes', now(), now(), '1', 'Heath Care Provider');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Lead Safe Housing Initiatives', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('lead safe illinois', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Leadership and Church Development', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Liberty Baptist', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Lilydale Baptist Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Lincoln United Methodist Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Little Brothers &acirc;&euro;" Friends of the Elderly, Chicago Chapter', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Lively Stone Missonary Baptist Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Living Well Ministries', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Lutheran Church of Atonement', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Lutheran Church of the Ascension', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Lutheran General Hospital &acirc;&euro;" Mission and Spiritual', now(), now(), '1', 'Heath Care Provider');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Lutheran Social Services of Illinois', now(), now(), '1', 'Community Organization');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('M.I.K.E. Minority Intervention and Kidney Education Program', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Ministry to New Moms', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Montrose Baptist Church', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Monument of Faith Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Mosque Foundation', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Mosque of Umar Inc.', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Most Blessed Trinity Church', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Mount Calvary Baptist Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Mount Pisgah Ministries', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Myanmar Christian Church of Metro Chicago', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('New Hope Bible Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('New Life Baptist Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('New Life Community Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('New Life Covenant Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('New Life Worship Center', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('New Mt.Pilgrim MB Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('New Pasadena MB Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('North Park Theological Seminary', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('North Shore Baptist Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('North Shore Church of Christ', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Northfield Presbyterian Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Northside P.O.W.E.R.', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Nuestra Senora de Gaudalupe', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Older Adult Programs', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Our Lady of Fatima Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Our Lady of Good Counsel', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Park Manor Church', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Park Ridge Community Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Peace Lutheran Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('People&acirc;&euro;&trade;s Church of the Harvest', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Peoples Church of Chicago', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Pilgrim Faith United Church of Christ', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Pillar of Love UCC', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Pleasant Ridge Baptist Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Polish Community', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Primera Iglesia Congregacional', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Program of Religion/Spirituality and Mental Health', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Progressive Baptist Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Pui Tak Center', now(), now(), '1', 'Community Organization');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Rahab's House, Inc.', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Rainbow Hospice and Palliative Care', now(), now(), '1', 'Community Organization');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Redeeming Life Family Worship Center COGIC', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Reformation Lutheran Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Revelation International Outreach Ministries', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Rush University Medical Center', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Salem Baptist', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Shiloh Baptist Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Shiloh Missionary Baptist Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Sinai Urban Health Institute', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('South Suburban Interfaith Ministerial Association', now(), now(), '1', 'Community Organization');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Spanish Christian Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('St Matthews United Methodist Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('St. Ailbe Catholic Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('St. Anne Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('St. Clement&acirc;&euro;&trade;s Episcopal Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('St. Francis of Assisi Church', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('St. Genevieve Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('St. Ita Catholic Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('St. James Lutheran Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('St. John MB Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('St. John United Church of Christ', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('St. Kevins&acirc;&euro;&trade;s Church', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('St. Luke's Lutheran of Logan Square', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('St. Luke&acirc;&euro;&trade;s Lutheran Church of Logan Square', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('St. Mark International Christian Ch.', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('St. Paul UCC', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('St. Paul&acirc;&euro;&trade;s Church by-the-Lake', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('St. Pius V. Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('St. Sabina Church', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('St. Stephen AME Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('St. Sylvester Catholic Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Suburban Chicago Interfaith Mental Health Coalition', now(), now(), '1', 'Community Organization');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Sunrise Missionary Baptist Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Temple of Faith Missionary Baptist Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('The American Heart Association (AHA)', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('The Buddhist Temple of Chicago', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('The Christian Aerobics &amp; Fitness Association (CAFA)', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('The South Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('The Unversity of Illinois Medical Center for Women's Health Associates', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Third Baptist Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Triedstone Full Gospel Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Trinity AME Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Trinity United Church of Christ', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('True Worship Baptist Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Turning Point', now(), now(), '1', 'Community Organization');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Ubumama - Chicago', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('United Baptist Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('United Faith Missionary Baptist Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('United in Faith Church', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Unity Lutheran Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Unity Northwest Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Universal House of Refuge Center', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('University of Illinois&acirc;&euro;&trade; Division of Community Health', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Victory Christian Assembly Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('VOCMA Faith Community Baptist Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Wesley United Methodist Church', now(), now(), '1', 'Faith Community/House of Worship');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Westside Health Authority', now(), now(), '1', '');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('Wholistic Medical Clinic', now(), now(), '1', 'Heath Care Provider');
insert into organization (name, create_dttm, activate_dttm, status_fk, type) values ('ZAM&acirc;&euro;&trade;s Hope Community Resource Center', now(), now(), '1', 'Community Organization');